### ISSUE TITLE
Problems with setFallbackLangForMissingTranslation

### ISSUE THREAD

**Issue by alexan** [ngneat/transloco#232]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm trying to `setFallbackLangForMissingTranslation` dynamically in my app and have found some strange behaviours:

1. when I am trying to set `translocoService.setFallbackLangForMissingTranslation({fallbackLang: 'en-US'})`. I am getting the following typescript error.
```
TS2345: Argument of type '{ fallbackLang: string | string[]; }' is not assignable to parameter of type 'TranslocoConfig'.   Property 'defaultLang' is missing in type '{ fallbackLang: string | string[]; }' but required in type 'TranslocoConfig'.
```
currently I am fixing this problem by casting the object to `TranslocoConfig`. But specifing a better type in your api would be better, as just fallbackLang is used by your code.

2. the implementation of `setFallbackLangForMissingTranslation` seems odd.

## Expected behavior
1. No typescript error when using the api as intended.
2. I think `this.useFallbackTranslation` should be a method invocation instead of just a boolean check. https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco/src/lib/transloco.service.ts#L374 .
You are dropping all fallbackTranslations if I am providing an array and just use the first value. The provided value should be used in the same way as if supplied via TranslocoConfig in setup and also available in `translocoService.config.fallbackLang`

## Minimal reproduction of the problem with instructions
1. here is a example of the error:
https://stackblitz.com/edit/transloco-example-swffsl?file=src%2Fapp%2Fapp.component.ts
2. fallbackLang should be shown, if accessed via config
https://stackblitz.com/edit/transloco-example-ngvf3t?file=src%2Fapp%2Fapp.component.html

## Environment
<pre><code>
Angular version: 7.3.9 
Typescript version: 3.2.4
</code></pre>

**Comment by shaharkazaz** [comment]
@alexan it's a type issue, I'll take care of it and update

**Comment by shaharkazaz** [comment]
@alexan I fixed the issues you raised in v2.13.5, LMK if something isn't working for you.

As for `setFallbackLangForMissingTranslation`, this function isn't used to set the fallback language, but to set the fallback **translation**, which is used in cases I have a missing key, an example: 
Let's say I have an active language of Japanese and I set the fallback translation to English, so when I have a missing Japanese key, the value will be taken from the English translation set.

I updated the docs in order to make it clearer, would be great if you check it out and tell me if it's clear enough now ([config](https://netbasal.gitbook.io/transloco/config-options) and [language API](https://netbasal.gitbook.io/transloco/service-api/language)).
The reason why we are taking the first value is since we currently support one fallback translation, and we don't really see the point of supporting more. (but if you do require this functionality you are welcome to open a PR for it)

**Comment by alexan** [comment]
Thanks for clearing this up. It is clearer now, but I'm not 100% sure if I would have understood the difference, If I would only look at the doku. 

One value there is enough for our use case. We are solving dialects with this functionality. When we have the language  `de-CH` (german as spoken in Switzerland) we want every value which is not present in the dialect to load from the base language `de-DE` 

Is it right that if I am setting  `missingHandler.useFallbackTranslation: true`. It will use the fist value from `fallbackTranslation` and is using this language the same as `setFallbackLangForMissingTranslation` ?

**Comment by shaharkazaz** [comment]
@alexan If you have any suggestions regarding the docs in order to make them clearer you are more than welcome to comment them here 🙂 
As stated in the docs, if you use `missingHandler.useFallbackTranslation: true`, it will take the first value from the `fallbackLang` property.
![image](https://user-images.githubusercontent.com/17194830/75674227-56862f00-5c8d-11ea-8b91-0a6e4aa5d5c8.png)
You can change the fallback translation via the service API via the `setFallbackLangForMissingTranslation` method.
