### ISSUE TITLE
Using Html tags inside translations

### ISSUE THREAD

**Issue by timhecker** [ngneat/transloco#303]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```json
{
     "name": "{{name}} is my name"
}
```

## Expected behavior

```json
{
      "name": "<strong>{{name}}</strong> is my name"
}
```

or something like that.

## What is the motivation / use case for changing the behavior?
Is there a way to use html tags inside text translations or interpolate them in some way?

Thanks

## Environment

<pre><code>
Angular version: 10.0.2

 
For Tooling issues:
- Node version: 12.18.2
- Platform:  Mac

**Comment by shaharkazaz** [comment]
@timhecker Please revisit our docs since this question is [answered there](https://ngneat.github.io/transloco/docs/faq#can-i-use-html-markings-inside-a-translation).
If you have any questions please try our [gitter lobby](https://gitter.im/ngneat-transloco/lobby) first, a lot of times you will find an answer there.

**Comment by timhecker** [comment]
Sorry, thank you very much!
