### ISSUE TITLE
Inline Loader not loading translations without translation in Template (Component Only Translating)

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco#327]
I've got a simple component that only needs to use translations inside the component and not in the template, but the inline loaders are never fired unless there is a translation in the template.

## Current behavior

```
import {
  Component,
  Inject,
  OnDestroy,
  OnInit,
} from "@angular/core";
import {
  translate,
  TranslocoService,
  TRANSLOCO_SCOPE,
} from "@ngneat/transloco";
import { Subscription } from "rxjs";
import { filter } from "rxjs/operators";
import { loader } from "scoped-loader";

@Component({
  selector: "app-demo",
  template: `app-demo works!`,
  providers: [
    {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        scope: "demo",
        loader,
      },
    },
  ],
})
export class DemoComponent implements OnInit, OnDestroy {
  private subscriptions$: Subscription = new Subscription();

  constructor(
    private translocoService: TranslocoService,
    @Inject(TRANSLOCO_SCOPE) private scope
  ) {}

  ngOnInit() {
    console.log("ng init");
    this.subscriptions$.add(
      this.translocoService.events$
        .pipe(
          filter(
            (e) =>
              e.type === "translationLoadSuccess" &&
              e.payload.scope === this.scope.scope
          )
        )
        .subscribe((e) => {
          console.log(e);
          console.log(translate('test'));
        })
    );
  }

  ngOnDestroy() {
    this.subscriptions$.unsubscribe();
  }
}
```

`translationLoadSuccess` is never fired

Altering the template to `<ng-container *transloco="let t; read: 'demo'">app-demo works!</ng-container>` makes it work.

## Expected behavior

I would expect that the translations should be loaded even if they are not used in the template, or if they are used in the component only.

**Comment by shaharkazaz** [comment]
@ChazUK If I understand you correctly this is a scope only used by this component? 
Transloco only loads the translation when they are needed and that's why you are not getting the `translationLoadSuccess` event, it's not related to inline loaders.

The structural directive and pipes are loading the needed translation behind the scenes, if you only need it in the component you will need to load it yourself by calling [the load function](https://ngneat.github.io/transloco/docs/language-api/#load)
