### ISSUE TITLE
Performance impact question

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#373]
## I'm submitting a...

<pre><code>
[X ] Other... Please describe:
</code></pre>

Hi. Thank you for creating the best translation framework for Angular!

I have a quick question based on some preliminary observations. I'll create a follow-up ticket if necessary.

Scenario:
- I have an Angular library that contains a single component and an en.json file containing all values that need to be localized within that component. 
- I then import that library into my SPA and create an ngFor loop where I import the component from my library into  app.component.html a 100 times.
-  Can I expect performance to be the same if I compare it to instead having the localized text in my main SPA en.json file?

There is a working sample in production here:
https://www.traveliko.com

The hotel card is that library component. It takes quite some time to load the first time because the payload is large. If you then click on a hotel card, then go back to the homepage by clicking the traveliko logo in the top left corner. At this point, the data is already loaded for the homepage so no backend calls are necessary. You'll notice an approximate 5 second wait time when scripts are being furiously calculated before the homepage shows again.

Thank you

**Comment by shaharkazaz** [comment]
@bjornharvold Thanks for the compliment! 🙂 
Why do you think the loading overhead is related to the `en.json` inside the library? 
Have you tried to check the load time when the translations are part of the main SPA `en.json`?

**Comment by bjornharvold** [comment]
Hi @shaharkazaz 

I have not done a real timing test. However, the question came up once we started bundling i18n files within our Angular libraries. We have a particularly "intense" component, the hotel card which you can find here (www.traveliko.com), and we are loading about a 100 of them on our home page. Although no official timing was done by us, we all saw an increase in load times and had to add an extra loading state using your *transloco="let t; loadingTpl: ghostCard" which mitigated the user experience a bit. The question came up if loading up a component from a library where the component itself contains the transloco provider:

`providers: [
    {provide: TRANSLOCO_SCOPE, useValue: 'hotel-card-lib'}
  ]`

Does it truly only get loaded once out of 100 usages, like on our site, or does there exist more than a simple check to confirm it has already been loaded that would increase load times. 

We also tried to verify if, once the homepage has been completely drawn and we move to the hotel landing page (by clicking on any hotel card) and then back again to the home page by clicking on the traveliko logo in the top left corner, it would speed up the home page. Unfortunately, the user experience here is not good at all. Once clicking on the traveliko icon, the site is unresponsive for ~4.6s before the home page displays. All the data is already there and we can see that the app is just churning through Javascript.

We will do more rigorous testing on this card to find out all the bottlenecks. We are pretty certain some of the time is attributed to transloco.

Cheers

**Comment by shaharkazaz** [comment]
Hi @bjornharvold 

Regarding the translation file load, I'm not sure what you meant by:
> or does there exist more than a simple check to confirm it has already been loaded that would increase load times.

But as you stated, Transloco loads the file once and shares the value, so no overhead there. 
You do need to understand that putting these translations as a separate scope will make another network request, which is something to think about.

If you are thinking that transloco has a big part of the JS computing time, you can just remove the transloco directive and use plain strings in the card and see if the result changes dramatically. (you should see some change since you are reducing complexity by removing it).

I'm unaware of the implementation of the card, but here are some insights at first glance at your comment and the site:
* Why load 100 components when the site initiates? is there a reason for it? I suggest you load an initial 10 (or more items) and there rest load demand via virtual scrolling (or whatever suits your needs).
* There is a large number of network requests made when that site loads.

I think if you try and address those issues you will see a major improvement, I don't think that the performance issues are related to transloco.

If your investigation shows something else and you can point a connection to Transloco feel free to reopen and share the results here and we can address them.
