### ISSUE TITLE
Documentation: How to use within (lazy loaded) feature modules

### ISSUE THREAD

**Issue by MickL** [ngneat/transloco#432]
### Is your feature request related to a problem? Please describe.
The docs only say that `ng add @ngneat/transloco` adds `TranslocoRootModule` into `AppModule`. But now if I want to use `<ng-container *transloco="let t"></ng-container>` within a lazy loaded feature module it displays nothing at all. The docs dont state how to use/import `TranslocoRootModule` in feature modules at all.

I tried:
- Import `TranslocoRootModule` only in app module (no error but displays nothing at all)
- Import `TranslocoRootModule` in my shared module (no error but displays nothing at all)
- Import `TranslocoRootModule` in my shared module and export it (injection error)
- Import `TranslocoRootModule` in each feature module (injection error)
- Import `TranslocoRootModule` in app module AND each feature module (works)

### Describe the solution you'd like
Add informations to the docs what is the best practice for (lazy loaded) feature modules.

P.S. I dont want to open an issue but it would be nice if the docs could also state why structural directives are the recommended approach for translations in templates and why pipes are not.

**Comment by shaharkazaz** [comment]
@MickL I think you are having a small confusion between the `TranslocoRootModule` and the `TranslocoModule`.
The `TranslocoRootModule` should only exist in your `AppModule` (as the schematics do for you).

If you need access to any of the transloco directives or services, just like any other module you need to import the `TranslocoModule` and make it available in the module's scope.

The `TranslocoRootModule` exports the `TranslocoModule` which makes it available to anything in the `AppModule`'s scope, in your lazy loaded module you need to import the `TranslocoModule`.

As for your P.S, the [docs](https://ngneat.github.io/transloco/docs/translation-in-the-template#structural-directive) states the following:

> It's DRY and efficient, as it creates one subscription per template:

Using the structural directive keeps your template (which can get messy, to begin with) cleaner and DRY.
Furthermore, it's more efficient as it creates one subscription for language changes instead of one per pipe.

**Comment by MickL** [comment]
> The `TranslocoRootModule` exports the `TranslocoModule` which makes it available to anything in the `AppModule`'s scope, in your lazy loaded module you need to import the `TranslocoModule`.

Ah, see! Thats exactly the information that is missing in the docs. I didnt know there is a `TranslocoModule` :)

**Comment by shaharkazaz** [comment]
I have to say that this is the first time the question has been raised. If I see that this comes up again, I'll think of a way to make a clearer example.

**Comment by MickL** [comment]
Made a PR: https://github.com/ngneat/transloco/pull/436

**Comment by keithcarter5** [comment]
Module federation requires (or best practice, at least) parents (shell apps) should not import app modules from microfrontends.  Consequently, my app needs to be able to inject Transloco into root from outside of AppModule.  I would really appreciate this as a new feature.

**Comment by Predhin** [comment]
+1
