### ISSUE TITLE
Getting started guide does not work on new project

### ISSUE THREAD

**Issue by tleveque23** [ngneat/transloco#437]
I created a brand new Angular project using the Cli and followed the guide in the "Getting Started" section of the doc.
> ng n translocotest
> cd translocotest
> ng add @ngneat/transloco
Choosing en,es,fr has the available languages and fr has the default one.
Added a direct translation in the ngOnInit method in the AppComponent class. Added the translations in the json files.
> ng serve
And it does not work. In the console I have the message: "Missing translation for 'titre'"
And I can see in the network tab that the json file is never loaded.
Also, if I try to use something like 
{{ t('titre') }}
It does not compile. " Property 't' does not exist on type 'HomeComponent'."

You can look at my test project on Stackblitz:
https://stackblitz.com/github/tleveque23/translocotest?file=src%2Fassets%2Fi18n%2Fen.json

**Comment by shaharkazaz** [comment]
@tleveque23 Please read the [docs](https://ngneat.github.io/transloco/docs/translation-api#translate) more carefully, either load the translation or use `selectTranslate`.

Please read the entire documentation or at least the part related to the API you are using, a lot of time was spent to make them as clear as possible.

If you have further questions please refer to our gitter channel or open a discussion instead of an issue.
