### ISSUE TITLE
Bug: inlineLang does not work properly after setActiveLang call

### ISSUE THREAD

**Issue by artaommahe** [ngneat/transloco#463]
### Current behavior
Changing current lang via `translocoService.setActiveLang()` changes directive/pipe translations despite `inlineLang` using.

### Expected behavior
`inlineLang` should always have more priority than current global lang.

### Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngneat-transloco-inline-lang-bug?file=src%2Fapp%2Fhome%2Fhome.component.html

- both text blocks by default are in english. First one due to global en lang, second due to `inlineLang: 'en'` usage via directive and pipe
- click `Spanish` button
- both text blocks are in spanish now, ignoring  `inlineLang: 'en'` in the second one

### Transloco config

default from transloco playground

### Environment
<pre><code>- Transloco version: 2.21.0
- Angular version: 11.2.4
</code></pre>

### Browser:
- [x] Chrome (desktop) version 91.0.4472.106 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[x] Maybe next time

**Comment by shaharkazaz** [comment]
I think this is what you want: https://ngneat.github.io/transloco/docs/multi-lang/

**Comment by artaommahe** [comment]
i don't understand. Im already using lang input in pipe and it is ignored if global lang is changed

**Comment by Ludevik** [comment]
@shaharkazaz pointed to docs where it is explained. I must admit i missed it too, that's why i'm here :)

Note this sentence in the docs:
Note that it will be used as the **initial** language. If you need it to be static, you can use the static pipe:

I have updated your stackblitz: https://stackblitz.com/edit/ngneat-transloco-inline-lang-bug-ftm5vp

The idea is to use `en|static`. However i am not sure how to use `static` with pipe:

`{{ 'hello' | transloco:{}:'en|static' }}` doesn't seem to do the trick.

**Comment by artaommahe** [comment]
Thx, so this is not the bug. But clearly there is a problem with ignored `|static` in transloco pipe. @shaharkazaz what about this thing?
