### ISSUE TITLE
Change private to protected methods in TranslocoDirectiveBase

### ISSUE THREAD

**Issue by angelaki** [ngneat/transloco#489]
My application is using objects implementing an interface `Translateable`, having a translate key or, if not present, a fallback-value. My idea was to use my own directive extending `TranslocoDirectiveBase` and pick the translate key or directly return the value if no key is present.

For this I'd need to override `private getTranslateFn(lang: string, read: string | undefined): (key: string, params?: HashMap)`

Or is there already a better approach for this? Right now everywhere I'm using this markup:

`{{ m.displayTextTranslation ? t(m.displayTextTranslation) : m.displayText }}`

and I'd like to be able to say `{{ t(m) }}` where m is my `Translateable`.

**Comment by rafaelss95** [comment]
I think that I have a similar case, so I'm posting it here. In order to avoid mistakes like writing a key wrongly or something like that, I generate a `d.ts` from the `.json` with all possible keys. It seems like this:

```ts
type TranslationKeys = 'a' | 'b.c.d' | '...';
```

However, unfortunately, I can't have the benefits from type-checking as `TranslocoDirective` accepts any `string`... so, I might be wrong, but for this case I described, a simple generic for `TranslocoDirective` would be sufficient:

```diff
- export class TranslocoDirective implements OnInit, OnDestroy, OnChanges {
+ export class TranslocoDirective<TKeys extends string = string> implements OnInit, OnDestroy, OnChanges {

- private getTranslateFn(lang: string, read: string | undefined): (key: string, params?: HashMap) => any {
+ private getTranslateFn(lang: TKeys, read: string | undefined): (key: string, params?: HashMap) => any {
```

so I'll be able to override/extend the directive like this:

```ts
@Directive({ selector: '[transloco]' })
class StronglyTypedTranslocoDirective extends TranslocoDirective<TranslationKeys> {}
```

[**Playground**](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqBOYB2EQHthoCIEt4FNgAXHAN3wB5Zp8API-JAExgiPhyQHNoBeaNh24A+aAG8AUNGhd8RBMlRgGAMSQAKcNwBccAJTip06JhRoQ+AHToum5Fz0BuIwF8JbiUQCeAB3xxEFHASNCQAaXwvGH4AcjAY6AAfaBiAI0tgSyYY5wlQSBgAUXpGJnwmBSCMbDxCEnIaEuYYStRq3AJiMkpW4JxQiKjRMWgPJHwAd2hihmZy3vbarvJ1PUtZeUClVQ04mKcJcamZ0vmt9EwOuu7V9ble5Xw1dTT9x2gAeg-oVOgmNHwMCQaCIjRwbGgnGgAAMHiFwpEINCgA)

**Comment by angelaki** [comment]
Since typescript wouldn't mind changing the overridden method's parameters having a protected `getTranslateFn` would solve your problem, too. I guess your use-case is a bit too specific to become part of the main lib.

**Comment by rafaelss95** [comment]
> Since typescript wouldn't mind changing the overridden method's parameters having a protected getTranslateFn would solve your problem, too.

You're correct, both solutions would work.

> I guess your use-case is a bit too specific to become part of the main lib.

What I proposed was a simple addition of `TypeParameter`, which defaults to `string`... I don't see how this could impact the lib in any way as it generates no additional code at all or breaks something. That wouldn't just benefit my project, but that of anyone who wants to have their strings being checked statically, rather than just praying they're correct and doesn't break at runtime.

---

That said, I don't really care about the approach, as in the end it will all solve the problem (although this will generate a little more code just to get type-checking working, but ok 🤷🏽‍♂️). With the way you proposed it would look like this:

```ts
// Missing `@Input()`
@Directive({ selector: '[transloco]' })
class StronglyTypedTranslocoDirective extends TranslocoDirective {
  override getTranslateFn(lang: TranslationKeys) {
    super.getTranslateFn(lang);
  }
}
```

[**Playground**](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqBOYB2EQHthoCIEt4FNgAXHAN32gG8AoaaAB3jSMJYBNoBzfIhZVMCwBiSABTgknAFzQIReDkkBKKrTrRMKNCHwA6dJ3HJOSgNxqAvtSvUiAT3oU+KcCTRIA0vjswAvNAByMADoAB9AgCNdYF02APNqUEgYAFEADxYkNnw2Z1QMbDxWMgp8DPwsmDz0TFwCYhLVOjRyeAVsrh5qwXwRI0kZbrdPbwgVGnVZAFdHeF1uXkQXHr6JE3M6KxskfAB3aHTM7Nyl-NqihvJRJXmu09desSCAs2od-cOK4+qCuuKrm4LIaPUQBCIvUzQAD0UOgEWgbDQ+BgSGY0DKODk0EU0AABkMcO4vD5cUA)

**Comment by angelaki** [comment]
Yeah, sure! I like your idea! But since an extension of `TranslocoDirective` would be required anyway I guess it's more up to the user to implemented it if really needed. Guess it just complicates the lib unnecessarily. But that's just my opinion! Should the devs decide. We just need this method to be protected, so there's no need to hack around ;)

Would you be so nice and create a PR? Otherwise I could do it, just a bit busy right now.

**Comment by rafaelss95** [comment]
Done, @angelaki. See #492.

**Comment by angelaki** [comment]
Any reason / idea why this isn't merget, yet? Guess it's not that risky ;)
