### ISSUE TITLE
Multiple languages / switch language in component independently from main language

### ISSUE THREAD

**Issue by idroxid** [ngneat/transloco#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

I have a basic parent-child components UI.
The app is available in multiple languages.
One of the components is a document editor, and need to be translated independently from the main app UI.

So, I use transloco in order to translate my interface.
`<ng-container *transloco="let t">`

I can switch languages for the main interface (parent component) with `setActiveLang()`

The child component uses a dynamic variable to define its language:
`<ng-container *transloco="let t; lang: childLanguage">`

The parent is showing the expected language, so do the child component.
When I switch language for the parent, it changes the language for the child too.

### Expected behavior

What I try to do is when I change the main language, it does not change the child language.
I know that this is possible using the `static` option.
But I also need to switch languages in the child component, independently from the parent (the main interface).

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-heava7

### Please provide the environment you discovered this bug in

```markdown
Transloco: 3.1.1
Angular: 12.2.15
Node: 16.13.1
Package Manager: npm
OS: Docker
```

### Browser

```markdown
Chrome 97.0.4692.71
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@idroxid I'm not sure if you noticed but your reproduction won't work if you are using OnPush in the child component.
You are actually experiencing a different issue, the transloco structural directive isn't updating on lang input change.
If he was reacting to these changes using the `childLang + '|static'` would have done the trick for you.
Now, this is a larger issue since I need to think about what's the desired behavior here.

I can offer you a solution in the meantime, you can add a structural directive that recreates the child when the lang changes.
See this [basic implementation](https://stackblitz.com/edit/angular-ivy-yok98w?file=src%2Fapp%2Fapp-change-child-lang.directive.ts) of the idea.

**Comment by idroxid** [comment]
@shaharkazaz thank you for your feedback!
> If he was reacting to these changes using the childLang + '|static' would have done the trick for you.
Yep, that's what I was expecting.

> Now, this is a larger issue since I need to think about what's the desired behavior here.
Yes, I can imagine.

Thank you for your solution. 
I'm actually respawning the overall child component and it works well too.

Many thanks again !
