### ISSUE TITLE
Bug(unit testing with pipe): issue in a unit test using a transloco pipe

### ISSUE THREAD

**Issue by eilensm** [ngneat/transloco#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

transloco pipe does returns empty string;

see the Readme of the provided repo for more information on the context

### Expected behavior

transloco pipe returns translated text

### Please provide a link to a minimal reproduction of the bug

https://github.com/eilensm/transloco-test-issue

### Transloco Config

```markdown
see github project
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 3.1.4
Angular: 13.2.0
Node: v16.13.1
Package Manager: npm 8.5.3
OS: Windows 10
```

### Browser

```markdown
Chrome Version 99.0.4844.74
```

### Additional context

see Readme of the provided repo

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@eilensm Since you are preloading all the langs, you need to provide the testing modules with **all** the langs, including the scoped ones.
Here is a fix for your reproduction:
```ts
// transloco-testing.module.ts

import { TranslocoTestingModule, TranslocoTestingOptions } from "@ngneat/transloco";
import de from "../assets/i18n/de.json";
import en from "../assets/i18n/en.json";
import bEn from "./b/assets/i18n/en.json";
import bDe from "./b/assets/i18n/de.json";

export function getTranslocoModule(options: TranslocoTestingOptions = {}) {
  return TranslocoTestingModule.forRoot({
    langs: {
      en,
      de,
      'b/en': bEn,
      'b/de': bDe,
    },
    translocoConfig: {
      availableLangs: ["en", "de"],
      defaultLang: "en"
    },
    preloadLangs: true,
    ...options
  });
}

```

**Comment by eilensm** [comment]
Hi @shaharkazaz,

hmm, ok. 

But isn't this quite cumbersome, since module B is itself more or less self-contained and brings along its assets and configuration; thus, if I want to test sth. in module A, I have to know all assets of the required modules (in this example only module B, but there could also be some other modules)?

For sake of simplicity, we put module B in the same app here, but in our real setup, module B is an npm library, and depending on how this library is implemented, I may not even have access to the translations.

**Comment by eilensm** [comment]
Hi @shaharkazaz again ;)

One other thing I wanted to mention is, that the service, in contrast to the pipe, works.

I updated the GIT repo and added a test case showing this.

In app.component.spec.ts, there are these two tests demonstrating this behaviour:
- 'should render app title via pipe' : fails
- 'should render app title via service' : works

**Comment by shaharkazaz** [comment]
@eilensm This is a mocked Transloco module, so the definitions inside the modules (in your case Module B) themselves aren't relevant.
I would suggest that if you want to test Module B then create a specific test for it, That way each testing module is only aware of its own translations.

> module B is an npm library, and depending on how this library is implemented, I may not even have access to the translations.

Not sure why would you want to test a 3rd party lib in your app, especially its translations.

> One other thing I wanted to mention is, that the service, in contrast to the pipe, works.

You are misusing the scopes.
Please see the note at the beginning of the [scope documentation](https://ngneat.github.io/transloco/docs/scope-configuration).

Since you module B **isn't lazy-loaded** the scope provider is available at the App's component level, which means that the pipe is searching for `'helloWorld'` under `b/en`.
Please read the docs more carefully.

Moving the provider to the component level resolved the issue for the app level test.
Regarding the B component test, as I wrote before I would write a dedicated test for it instead of combining them.
Seems like there is some sort of race within the test, waiting for the rendering to be done resolves the issue:
```
    fixture.whenRenderingDone().then(() => {
      const compiled = fixture.nativeElement as HTMLElement;
      expect(compiled.querySelector('h2')?.textContent).toContain('Hello B world!');
    });
```
