### ISSUE TITLE
ng-add Path "undefined" does not exist

### ISSUE THREAD

**Issue by LukasKlement** [ngneat/transloco#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Schematics

### Is this a regression?

Yes

### Current behavior

ng add @ngneat/transloco does not work in angular 17.

In a new Angular project (ng new test), running ng add @ngneat/transloco gives the error Path "undefined" does not exist

### Expected behavior

ng add @ngneat/transloco shoudl work

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

-

### Please provide the environment you discovered this bug in

```markdown
Transloco: 6
Angular: 17
Node: 18
Package Manager: npm
OS: macOS
```

### I would like to make a pull request for this bug

No

**Comment by ilMike42** [comment]
Same thing happening to me, clean project created with `ng new angular-frontend`, me too using Angular 17, Node 18 and Transloco 6 (but Transloco 5.0.10 same thing).

**Comment by mahmoud4489** [comment]
The same thing happens to me too and I don't know why

Angular CLI: 17.0.1
Node: 18.18.0
Package Manager: npm 9.8.1
OS: win32 x64

**Comment by mahmoud4489** [comment]
Anyone have a solution?

**Comment by skazaz-utila** [comment]
I'll try to take a look today

**Comment by shaharkazaz** [comment]
I'll try to take a look today

**Comment by jramassamy** [comment]
Thanks Shahar ^^ !

**Comment by dieperid** [comment]
Hello, any news on this topic ?
I have the same issue on my side.

Transloco: 6
Angular CLI: 17.0.3
Node: 21.2.0
Package Manager: npm 10.2.3
OS: Debian

**Comment by YuliyaBialova** [comment]
> I've tested on both v16 and v17 projects, and it works as expected 👍 
> 
> LMK if there are any issues

Shahar, thank you so much 😇😇😇☺️☺️☺️☺️

**Comment by Milly00** [comment]
hi i have been the same issue at moment of use "ng add @angular/pwa" to resolve I updated the version of angular cli and  dissapear the error.

**Comment by davisriska** [comment]
Im also experiencing this issue "Path "undefined" does not exist.". The only thing I can imagine is that I don't really have a standard project structure. 

```
"newProjectRoot": "resources",
    "projects": {
        "frontend": {
            "projectType": "application",
            "root": "./",
            "sourceRoot": "resources/frontend",
```
Maybe this has something to do with it?

**Comment by dzcora** [comment]
> I've tested on both v16 and v17 projects, and it works as expected 👍 LMK if there are any issues

Hi it's not work for me with V17
Node v18.13.0
Mac
 "@ngneat/transloco": "^6.0.4",
 Nx workspace

**Comment by dzcora** [comment]
@shaharkazaz

**Comment by shaharkazaz** [comment]
@davisriska @dzcora Please share a reproduction as the original issue was already resolved.

**Comment by berkon** [comment]
Still getting this issue with Angular 18.1.4.

**Comment by shaharkazaz** [comment]
@berkon I might be missing something, but how is running the `angular/pwa` schematics related to this issue or Transloco?

**Comment by berkon** [comment]
@shaharkazaz, you are right, I was just looking at the title and my error message is exactly the same. I didn't notice that it was about transloco.

BTW: My findings showed that it looks like this issue happens when there is something not compliant to the standard Angular workspace/project settings/file structure etc. . When generating a clean project from scratch it worked well. Unfortunately the error message is really useless.

**Comment by jeffreyvanelderen** [comment]
I will put this here for anyone else having this issue in the future (unrelated to transloco, but triggers when trying to install using ng-add)

Had the same issue with a fresh Angular 19 project. Managed to find what was causing it, since the error is really vague. In `angular.json`, I had changed the builder from the default `@angular-devkit/build-angular:application` to `@ngx-env/builder:application` since I used [another library for .env support](https://www.npmjs.com/package/@ngx-env/builder). 

Apparantly, changing the builder here broke my ng-add setup command for transloco. Changing the builder back to the default one ( `@angular-devkit/build-angular:application`) immediately fixed the setup command... (You might need to fully revert your angular.json to use the default angular builder)

<img width="640" alt="Image" src="https://github.com/user-attachments/assets/b5a87297-b00c-4aa3-bd06-4f4bf3c20e46" />

Terminal:

```
% ng add @jsverse/transloco
Skipping installation: Package already installed
✔ 🌍 Which languages do you need? en, nl, fr
✔ 🚀 Are you working with server side rendering? No
Path "undefined" does not exist.

/// Changed the builder path in angular.json back to default

% ng add @jsverse/transloco
Skipping installation: Package already installed
✔ 🌍 Which languages do you need? en, nl, fr
✔ 🚀 Are you working with server side rendering? No
CREATE transloco.config.ts (232 bytes)
CREATE src/app/transloco-loader.ts (424 bytes)
CREATE src/assets/i18n/en.json (3 bytes)
CREATE src/assets/i18n/nl.json (3 bytes)
CREATE src/assets/i18n/fr.json (3 bytes)
UPDATE src/app/app.config.ts (1754 bytes)
% 

```

Angular.json changes I did which changes your default builder in the whole file:

<img width="1327" alt="Image" src="https://github.com/user-attachments/assets/33d93bae-187e-4522-93a8-7f709dd1399c" />
